sudo: false
language: C
services:
  - docker
  # MySQL cannot be added as an addon to a certain job, so added
  # as a service. A job w/o an addon has MySQL installed and
  # started, while a job with MariaDB addon will delete MySQL,
  # install and start MariaDB.
  - mysql

cache:
    directories:
      - $HOME/.cache

env:
  global:
    - PRODUCT=tarantool-mysql

jobs:
  include:
    - name: "Run tests on MySQL"
    - name: "Run tests on MariaDB"
      addons: {mariadb: '10.4'}
    - name: "CentOS 6 build + deploy RPM"
      env: OS=el DIST=6
    - name: "CentOS 7 build + deploy RPM"
      env: OS=el DIST=7
    - name: "CentOS 8 build + deploy RPM"
      env: OS=el DIST=8
    - name: "Fedora 28 build + deploy RPM"
      env: OS=fedora DIST=28
    - name: "Fedora 29 build + deploy RPM"
      env: OS=fedora DIST=29
    - name: "Fedora 30 build + deploy RPM"
      env: OS=fedora DIST=30
    - name: "Fedora 31 build + deploy RPM"
      env: OS=fedora DIST=31
    - name: "Ubuntu Trusty (14.04) build + deploy DEB"
      env: OS=ubuntu DIST=trusty
    - name: "Ubuntu Xenial (16.04) build + deploy DEB"
      env: OS=ubuntu DIST=xenial
    - name: "Ubuntu Bionic (18.04) build + deploy DEB"
      env: OS=ubuntu DIST=bionic
    - name: "Ubuntu Focal (20.04) build + deploy DEB"
      env: OS=ubuntu DIST=focal
    - name: "Debian Jessie (8) build + deploy DEB"
      env: OS=debian DIST=jessie
    - name: "Debian Stretch (9) build + deploy DEB"
      env: OS=debian DIST=stretch
    - name: "Debian Buster (10) build + deploy DEB"
      env: OS=debian DIST=buster

script:
  - |
    if [ -n "${OS}" ] && [ -n "${DIST}" ]; then
        git describe --long;
        git clone https://github.com/packpack/packpack.git packpack;
        packpack/packpack;
    else
        ./.travis/test.sh;
    fi;

before_deploy:
  - ls -l build/

deploy:
  # Deploy packages to PackageCloud
  - provider: packagecloud
    username: tarantool
    repository: "1_10"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2x"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_2"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_3"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_4"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"

  # Deploy packages to PackageCloud from tags
  # see:
  #   * https://github.com/tarantool/tarantool/issues/3745
  #   * https://github.com/travis-ci/travis-ci/issues/7780#issuecomment-302389370
  - provider: packagecloud
    username: tarantool
    repository: "1_10"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      tags: true
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2x"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      tags: true
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_2"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      tags: true
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_3"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      tags: true
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_4"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      tags: true
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"

notifications:
  email:
    recipients:
      - build@tarantool.org
    on_success: change
    on_failure: always
